# Catching Exceptions

Exceptions can be caught with standard `try ... catch` blocks like in this example. There is a bug in our `return8()` function that is discovered by the `T6.eq()` method. Since we caught the error, the script continues to run normally.